Project1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from caridok.views import listPesanan
from bmi.views import  bmi_func

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = 'homepage'),
    path('feedback/', include('feedback.urls')),
    path('cariDok/', include('caridok.urls')),
    path('cariDok/',include('buatDok.urls')),
    path('tanyadok/', include('tanyadok.urls')),
    path('listPesanan/', listPesanan, name='listPesanan'),
    path('accounts/', include('user.urls')),
    path('berita/', include('berita.urls')),
    path('bmi/',bmi_func, name='BMIPage'),
    path('penyakit/', include('penyakit.urls')),
]

user/urls.py
from django.urls import path, include
from . import views
from user.forms import LoginForm

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view,name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('signup/', views.signup_view, name="signup"),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate

from user.forms import LoginForm, SignUpForm

# Create your views here.

def login_view(request) :
    if request.method == 'POST':
        form = LoginForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('homepage')
    else:
        form = LoginForm()
    
    return render(request, 'login.html', {'form': form})

def logout_view(request) :
    if request.method == 'GET':
        logout(request)
        return redirect('homepage')

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('homepage')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

user/templates/login.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="{% static "vendor/bootstrap/bootstrap.css " %}">
    <link rel="stylesheet" href="{% static "css/index.css " %}">

</head>

<body>
    <div class="container" style="margin-top: 100px;">
        <div class="row justify-content-center">
            <div class="card col-md-6 " style="margin-top: 20px;">
                <h5 class="card-header info-color white-text text-center py-4">
                    <strong>Sign in</strong>
                </h5>
                <div class="card-body">
                    <form action="{%url 'user:login'%}" method="post">
                        {%csrf_token%} {{ form.as_p }}
                        <input class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit" value="login">
                        <p>Not a member?
                            <a href="/accounts/signup/">Register</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

user/templates/signup.html
{% extends "base.html" %} {% block content %}

<div class="container">
    <div class="container" style="margin-top: 100px;">
        <div class="row justify-content-center">
            <div class="card col-md-6 " style="margin-top: 20px; margin-bottom: 50px;">
                <h5 class="card-header info-color white-text text-center py-4">
                    <strong>Sign up</strong>
                </h5>
                <div class="card-body col-12">
                    <form method="POST">
                        {% csrf_token %} {% for field in form %}
                        <div>
                            <div>
                                {{field.label_tag}}
                            </div>
                            {{field}}
                        </div>

                        {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %} {% endfor %}
                        <button type="submit" style="margin-top: 20px;">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock content %}